### ISSUE TITLE
Add optional support

### ISSUE THREAD

**Issue by sgerbino** [koinos/koinos-types#174]
As a Koinos engineer, I would like to support optional members in all languages.

- [x] Modify C++ Jinja templates (#192)
- [x] Modify Golang Jinja templates (#193)
- [x] Add optional to C++ tests (#194)
- [x] Add optional to Golang tests (#195)
- [x] Make BlockItem.block an optional (#196)

**Note:** We want to support behavior similar to `std::optional<>` in C++ for `koinos-types`.
